// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $("#auth_token").on('change', function(e) {
      var token;
      token = $("#auth_token").val();
      return $.ajax({
        url: "https://api.todoist.com//API/getProjects",
        type: "GET",
        dataType: "jsonp",
        data: {
          token: token
        },
        success: function(data) {
          $("#projects").empty();
          return $.each(data, function(i, project) {
            return $("#projects").append($("<option>").html(project.name).val(project.id));
          });
        }
      });
    });
    return $("#projects").on('change', function(e) {
      var project_id, token;
      project_id = $("#projects").val();
      token = $("#auth_token").val();
      return $.ajax({
        url: "https://api.todoist.com/API/getUncompletedItems",
        type: "GET",
        dataType: "jsonp",
        data: {
          token: token,
          project_id: project_id
        },
        success: function(data) {
          var tasks;
          tasks = [];
          $.each(data, function(i, params) {
            var from, matches, name;
            console.log(params.content);
            matches = params.content.match(/^(.*)\(([0-9]{4}-[0-9]{2}-[0-9]{2})\)$/);
            if (matches) {
              name = matches[1];
              from = Date.parse(matches[2]);
            } else {
              name = params.content;
              from = new Date();
            }
            return tasks.push({
              name: name,
              values: [
                {
                  from: "/Date(" + from + ")/",
                  to: "/Date(" + (Date.parse(params.due_date)) + ")/",
                  label: ""
                }
              ]
            });
          });
          console.log(tasks);
          return $(".gantt").gantt({
            source: tasks
          });
        },
        navigate: "scroll",
        maxScale: "hours",
        itemsPerPage: 20,
        onItemClick: function(data) {},
        onAddClick: function(dt, rowId) {},
        onRender: function() {}
      });
    });
  });

}).call(this);
